### ISSUE TITLE
TRAVIS ISSUE => Unfortunately, an unexpected error occurred, and Bundler cannot continue. fatal: No live threads left. Deadlock?

### ISSUE THREAD

**Issue by dearshrewdwit** [makersacademy/takeaway-challenge#202]
I don't know how to troubleshoot this. I've run bundle, looked at other Gemfiles and travis files etc on other passing repos, but can't resolve the issue. 

Copy pasted travis build log details.

``` 
Using worker: worker-linux-docker-84c9647d.prod.travis-ci.org:travis-linux-4
Build language: ruby
Build image provisioning date and time
Thu Feb  5 15:09:33 UTC 2015
Operating System Details
Distributor ID:	Ubuntu
Description:	Ubuntu 12.04.5 LTS
Release:	12.04
Codename:	precise
Linux Version
3.13.0-29-generic
Cookbooks Version
a68419e https://github.com/travis-ci/travis-cookbooks/tree/a68419e
GCC version
gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3
Copyright (C) 2011 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
LLVM version
clang version 3.4 (tags/RELEASE_34/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
Pre-installed Ruby versions
ruby-1.9.3-p551
Pre-installed Node.js versions
v0.10.36
Pre-installed Go versions
1.4.1
Redis version
redis-server 2.8.19
riak version
2.0.2
MongoDB version
MongoDB 2.4.12
CouchDB version
couchdb 1.6.1
Neo4j version
1.9.4
RabbitMQ Version
3.4.3
ElasticSearch version
1.4.0
Installed Sphinx versions
2.0.10
2.1.9
2.2.6
Default Sphinx version
2.2.6
Installed Firefox version
firefox 31.0esr
PhantomJS version
1.9.8
ant -version
Apache Ant(TM) version 1.8.2 compiled on December 3 2011
mvn -version
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T17:29:23+00:00)
Maven home: /usr/local/maven
Java version: 1.7.0_76, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-7-oracle/jre
Default locale: en_US, platform encoding: ANSI_X3.4-1968
OS name: "linux", version: "3.13.0-29-generic", arch: "amd64", family: "unix"
git.checkout
0.34s$ git clone --depth=50 --branch=master https://github.com/dearshrewdwit/takeaway-challenge.git dearshrewdwit/takeaway-challenge
Cloning into 'dearshrewdwit/takeaway-challenge'...
remote: Counting objects: 217, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 217 (delta 1), reused 0 (delta 0), pack-reused 208
Receiving objects: 100% (217/217), 57.38 KiB | 0 bytes/s, done.
Resolving deltas: 100% (88/88), done.
Checking connectivity... done.
$ cd dearshrewdwit/takeaway-challenge
$ git checkout -qf 1e05ddb711130096600ddb46b00fd76879a79d69
This job is running on container-based infrastructure, which does not allow use of 'sudo', setuid and setguid executables.
If you require sudo, add 'sudo: required' to your .travis.yml
See http://docs.travis-ci.com/user/workers/container-based-infrastructure/ for details.
ruby-2.2.3 is not installed - installing.
Searching for binary rubies, this might take some time.
Found remote file https://s3.amazonaws.com/travis-rubies/binaries/ubuntu/12.04/x86_64/ruby-2.2.3.tar.bz2
Checking requirements for ubuntu.
Requirements installation successful.
ruby-2.2.3 - #configure
ruby-2.2.3 - #download
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 21.1M  100 21.1M    0     0  73.2M      0 --:--:-- --:--:-- --:--:-- 73.8M
No checksum for downloaded archive, recording checksum in user configuration.
ruby-2.2.3 - #validate archive
ruby-2.2.3 - #extract
ruby-2.2.3 - #validate binary
ruby-2.2.3 - #setup
ruby-2.2.3 - #gemset created /home/travis/.rvm/gems/ruby-2.2.3@global
ruby-2.2.3 - #importing gemset /home/travis/.rvm/gemsets/global.gems................................................
ruby-2.2.3 - #generating global wrappers........
ruby-2.2.3 - #uninstalling gem rubygems-bundler-1.4.4.
ruby-2.2.3 - #gemset created /home/travis/.rvm/gems/ruby-2.2.3
ruby-2.2.3 - #importing gemset /home/travis/.rvm/gemsets/default.gems....................
ruby-2.2.3 - #generating default wrappers........
chown: changing ownership of `/home/travis/.rvm/user/installs': Operation not permitted
Using /home/travis/.rvm/gems/ruby-2.2.3
$ export BUNDLE_GEMFILE=$PWD/Gemfile
$ ruby --version
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]
$ rvm --version
rvm 1.26.10 (latest-minor) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
$ bundle --version
Bundler version 1.10.6
$ gem --version
2.4.8
before_install
0.00s$ sed -i '2d' Gemfile
63.99s$ bundle install --jobs=3 --retry=3 --deployment
Fetching gem metadata from https://rubygems.org/............
Fetching version metadata from https://rubygems.org/..
Installing ast 2.1.0
Installing mime-types 2.6.1
Installing mini_portile 0.6.2
Installing rack 1.6.4
Installing json 1.8.3 with native extensions
Installing unf_ext 0.0.7.1 with native extensions
Installing netrc 0.10.3
Installing docile 1.1.5
Installing simplecov-html 0.10.0
Installing tins 1.6.0
Installing thor 0.19.1
Installing diff-lcs 1.2.5
Installing powerpack 0.1.1
Installing rainbow 2.0.0
Installing ruby-progressbar 1.7.5
Installing rspec-support 3.3.0
Using bundler 1.10.6
Installing rubocop-rspec 1.3.0
Installing parser 2.2.2.6
Installing rack-test 0.6.3
Installing nokogiri 1.6.6.2 with native extensions
Installing unf 0.1.4
Installing simplecov 0.10.0
Installing term-ansicolor 1.3.2
Installing rspec-core 3.3.2
Installing rspec-expectations 3.3.1
Installing rspec-mocks 3.3.2
Installing astrolabe 1.3.1
Installing domain_name 0.5.24
Installing rspec 3.3.0
Installing rubocop 0.34.1
Installing http-cookie 1.0.2
Installing rest-client 1.8.0
Installing coveralls 0.8.2
Installing xpath 2.0.0
Installing capybara 2.4.4
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?
  I ran the command `/home/travis/.rvm/gems/ruby-2.2.3/bin/bundle install --jobs=3 --retry=3 --deployment`
- What did you expect to happen?
  I expected Bundler to...
- What happened instead?
  Instead, what actually happened was...
Error details
    fatal: No live threads left. Deadlock?
      /home/travis/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/worker.rb:35:in `pop'
      /home/travis/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/worker.rb:35:in `deq'
      /home/travis/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/installer/parallel_installer.rb:93:in `process_specs'
      /home/travis/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/installer/parallel_installer.rb:74:in `call'
      /home/travis/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/installer/parallel_installer.rb:56:in `call'
      /home/travis/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/installer.rb:274:in `install_in_parallel'
      /home/travis/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/installer.rb:91:in `run'
      /home/travis/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/installer.rb:18:in `install'
      /home/travis/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/cli/install.rb:107:in `run'
      /home/travis/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/cli.rb:162:in `install'
      /home/travis/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /home/travis/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /home/travis/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /home/travis/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /home/travis/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/cli.rb:10:in `start'
      /home/travis/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/bin/bundle:20:in `block in <top (required)>'
      /home/travis/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
      /home/travis/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/bin/bundle:18:in `<top (required)>'
      /home/travis/.rvm/gems/ruby-2.2.3/bin/bundle:23:in `load'
      /home/travis/.rvm/gems/ruby-2.2.3/bin/bundle:23:in `<main>'
      /home/travis/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
      /home/travis/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
Environment
    Bundler   1.10.6
    Rubygems  2.4.8
    Ruby      2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]
    GEM_HOME  /home/travis/build/dearshrewdwit/takeaway-challenge/vendor/bundle/ruby/2.2.0
    GEM_PATH  
    RVM       1.26.10 (latest-minor)
    Git       1.8.5.6
Bundler settings
    jobs
      Set for your local app (/home/travis/build/dearshrewdwit/takeaway-challenge/.bundle/config): 3
    retry
      Set for your local app (/home/travis/build/dearshrewdwit/takeaway-challenge/.bundle/config): 3
    frozen
      Set for your local app (/home/travis/build/dearshrewdwit/takeaway-challenge/.bundle/config): "1"
    path
      Set for your local app (/home/travis/build/dearshrewdwit/takeaway-challenge/.bundle/config): "vendor/bundle"
    disable_shared_gems
      Set for your local app (/home/travis/build/dearshrewdwit/takeaway-challenge/.bundle/config): "1"
    gemfile
      Set via BUNDLE_GEMFILE: "/home/travis/build/dearshrewdwit/takeaway-challenge/Gemfile"
--- TEMPLATE END ----------------------------------------------------------------
Unfortunately, an unexpected error occurred, and Bundler cannot continue.
First, try this link to see if there are any existing issue reports for this error:
https://github.com/bundler/bundler/search?q=No+live+threads+left.+Deadlock%3F&type=Issues
If there aren't any reports for this error yet, please create copy and paste the report template above into a new issue. Don't forget to anonymize any private data! The new issue form is located at:
https://github.com/bundler/bundler/issues/new
The command "eval bundle install --jobs=3 --retry=3 --deployment" failed. Retrying, 2 of 3.
Fetching gem metadata from https://rubygems.org/............
Fetching version metadata from https://rubygems.org/..
Using ast 2.1.0
Using mime-types 2.6.1
Using mini_portile 0.6.2
Using rack 1.6.4
Using json 1.8.3
Using unf_ext 0.0.7.1
Using netrc 0.10.3
Using docile 1.1.5
Using simplecov-html 0.10.0
Using tins 1.6.0
Using thor 0.19.1
Using powerpack 0.1.1
Using rainbow 2.0.0
Using rspec-support 3.3.0
Using ruby-progressbar 1.7.5
Using rubocop-rspec 1.3.0
Using bundler 1.10.6
Using parser 2.2.2.6
Using nokogiri 1.6.6.2
Using rack-test 0.6.3
Using unf 0.1.4
Using simplecov 0.10.0
Using term-ansicolor 1.3.2
Using rspec-core 3.3.2
Using diff-lcs 1.2.5
Using astrolabe 1.3.1
Using xpath 2.0.0
Using domain_name 0.5.24
Using rspec-expectations 3.3.1
Using rspec-mocks 3.3.2
Using rubocop 0.34.1
Using capybara 2.4.4
Using http-cookie 1.0.2
Using rspec 3.3.0
Using rest-client 1.8.0
Using coveralls 0.8.2
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?
  I ran the command `/home/travis/.rvm/gems/ruby-2.2.3/bin/bundle install --jobs=3 --retry=3 --deployment`
- What did you expect to happen?
  I expected Bundler to...
- What happened instead?
  Instead, what actually happened was...
Error details
    fatal: No live threads left. Deadlock?
      /home/travis/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/worker.rb:35:in `pop'
      /home/travis/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/worker.rb:35:in `deq'
      /home/travis/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/installer/parallel_installer.rb:93:in `process_specs'
      /home/travis/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/installer/parallel_installer.rb:74:in `call'
      /home/travis/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/installer/parallel_installer.rb:56:in `call'
      /home/travis/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/installer.rb:274:in `install_in_parallel'
      /home/travis/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/installer.rb:91:in `run'
      /home/travis/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/installer.rb:18:in `install'
      /home/travis/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/cli/install.rb:107:in `run'
      /home/travis/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/cli.rb:162:in `install'
      /home/travis/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /home/travis/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /home/travis/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /home/travis/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /home/travis/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/cli.rb:10:in `start'
      /home/travis/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/bin/bundle:20:in `block in <top (required)>'
      /home/travis/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
      /home/travis/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/bin/bundle:18:in `<top (required)>'
      /home/travis/.rvm/gems/ruby-2.2.3/bin/bundle:23:in `load'
      /home/travis/.rvm/gems/ruby-2.2.3/bin/bundle:23:in `<main>'
      /home/travis/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
      /home/travis/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
Environment
    Bundler   1.10.6
    Rubygems  2.4.8
    Ruby      2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]
    GEM_HOME  /home/travis/build/dearshrewdwit/takeaway-challenge/vendor/bundle/ruby/2.2.0
    GEM_PATH  
    RVM       1.26.10 (latest-minor)
    Git       1.8.5.6
Bundler settings
    jobs
      Set for your local app (/home/travis/build/dearshrewdwit/takeaway-challenge/.bundle/config): 3
    retry
      Set for your local app (/home/travis/build/dearshrewdwit/takeaway-challenge/.bundle/config): 3
    frozen
      Set for your local app (/home/travis/build/dearshrewdwit/takeaway-challenge/.bundle/config): "1"
    path
      Set for your local app (/home/travis/build/dearshrewdwit/takeaway-challenge/.bundle/config): "vendor/bundle"
    disable_shared_gems
      Set for your local app (/home/travis/build/dearshrewdwit/takeaway-challenge/.bundle/config): "1"
    gemfile
      Set via BUNDLE_GEMFILE: "/home/travis/build/dearshrewdwit/takeaway-challenge/Gemfile"
--- TEMPLATE END ----------------------------------------------------------------
Unfortunately, an unexpected error occurred, and Bundler cannot continue.
First, try this link to see if there are any existing issue reports for this error:
https://github.com/bundler/bundler/search?q=No+live+threads+left.+Deadlock%3F&type=Issues
If there aren't any reports for this error yet, please create copy and paste the report template above into a new issue. Don't forget to anonymize any private data! The new issue form is located at:
https://github.com/bundler/bundler/issues/new
The command "eval bundle install --jobs=3 --retry=3 --deployment" failed. Retrying, 3 of 3.
Fetching gem metadata from https://rubygems.org/............
Fetching version metadata from https://rubygems.org/..
Using ast 2.1.0
Using mime-types 2.6.1
Using mini_portile 0.6.2
Using rack 1.6.4
Using json 1.8.3
Using unf_ext 0.0.7.1
Using netrc 0.10.3
Using docile 1.1.5
Using simplecov-html 0.10.0
Using tins 1.6.0
Using thor 0.19.1
Using powerpack 0.1.1
Using rainbow 2.0.0
Using rspec-support 3.3.0
Using ruby-progressbar 1.7.5
Using rubocop-rspec 1.3.0
Using bundler 1.10.6
Using parser 2.2.2.6
Using nokogiri 1.6.6.2
Using rack-test 0.6.3
Using unf 0.1.4
Using simplecov 0.10.0
Using term-ansicolor 1.3.2
Using rspec-core 3.3.2
Using astrolabe 1.3.1
Using xpath 2.0.0
Using domain_name 0.5.24
Using rubocop 0.34.1
Using capybara 2.4.4
Using http-cookie 1.0.2
Using diff-lcs 1.2.5
Using rest-client 1.8.0
Using rspec-expectations 3.3.1
Using rspec-mocks 3.3.2
Using coveralls 0.8.2
Using rspec 3.3.0
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?
  I ran the command `/home/travis/.rvm/gems/ruby-2.2.3/bin/bundle install --jobs=3 --retry=3 --deployment`
- What did you expect to happen?
  I expected Bundler to...
- What happened instead?
  Instead, what actually happened was...
Error details
    fatal: No live threads left. Deadlock?
      /home/travis/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/worker.rb:35:in `pop'
      /home/travis/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/worker.rb:35:in `deq'
      /home/travis/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/installer/parallel_installer.rb:93:in `process_specs'
      /home/travis/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/installer/parallel_installer.rb:74:in `call'
      /home/travis/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/installer/parallel_installer.rb:56:in `call'
      /home/travis/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/installer.rb:274:in `install_in_parallel'
      /home/travis/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/installer.rb:91:in `run'
      /home/travis/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/installer.rb:18:in `install'
      /home/travis/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/cli/install.rb:107:in `run'
      /home/travis/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/cli.rb:162:in `install'
      /home/travis/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /home/travis/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /home/travis/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /home/travis/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /home/travis/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/cli.rb:10:in `start'
      /home/travis/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/bin/bundle:20:in `block in <top (required)>'
      /home/travis/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
      /home/travis/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/bin/bundle:18:in `<top (required)>'
      /home/travis/.rvm/gems/ruby-2.2.3/bin/bundle:23:in `load'
      /home/travis/.rvm/gems/ruby-2.2.3/bin/bundle:23:in `<main>'
      /home/travis/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
      /home/travis/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
Environment
    Bundler   1.10.6
    Rubygems  2.4.8
    Ruby      2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]
    GEM_HOME  /home/travis/build/dearshrewdwit/takeaway-challenge/vendor/bundle/ruby/2.2.0
    GEM_PATH  
    RVM       1.26.10 (latest-minor)
    Git       1.8.5.6
Bundler settings
    jobs
      Set for your local app (/home/travis/build/dearshrewdwit/takeaway-challenge/.bundle/config): 3
    retry
      Set for your local app (/home/travis/build/dearshrewdwit/takeaway-challenge/.bundle/config): 3
    frozen
      Set for your local app (/home/travis/build/dearshrewdwit/takeaway-challenge/.bundle/config): "1"
    path
      Set for your local app (/home/travis/build/dearshrewdwit/takeaway-challenge/.bundle/config): "vendor/bundle"
    disable_shared_gems
      Set for your local app (/home/travis/build/dearshrewdwit/takeaway-challenge/.bundle/config): "1"
    gemfile
      Set via BUNDLE_GEMFILE: "/home/travis/build/dearshrewdwit/takeaway-challenge/Gemfile"
--- TEMPLATE END ----------------------------------------------------------------
Unfortunately, an unexpected error occurred, and Bundler cannot continue.
First, try this link to see if there are any existing issue reports for this error:
https://github.com/bundler/bundler/search?q=No+live+threads+left.+Deadlock%3F&type=Issues
If there aren't any reports for this error yet, please create copy and paste the report template above into a new issue. Don't forget to anonymize any private data! The new issue form is located at:
https://github.com/bundler/bundler/issues/new
The command "eval bundle install --jobs=3 --retry=3 --deployment" failed 3 times.
The command "bundle install --jobs=3 --retry=3 --deployment" failed and exited with 1 during .
Your build has been stopped.
```

**Comment by dearshrewdwit** [comment]
Thank goodness for Alumni Helpers. We don't really know how we resolved it apart from methodically trying different things. Downgrading Ruby versions, Twilio versions, upgrading both.

The only thing that was changed to make it pass was explicitly stating the version of twilio in the Gemfile

```
gem 'twilio-ruby', '~> 4.5.0'
 ```
